### ISSUE TITLE
License for packaging

### ISSUE THREAD

**Issue by jayvdb** [python-lml/lml#13]
I initially created the openSUSE .spec using [`py2pack`](https://pypi.org/project/py2pack/), and it injected the following into [the spec](https://build.opensuse.org/package/view_file/home:jayvdb:soe/python-lml/python-lml.spec?expand=1)

`License:        New BSD (FIXME:No SPDX)`

I havent fully investigated this yet, and it isnt mentioned in https://en.opensuse.org/openSUSE:Packaging_Python .

I have found https://github.com/openSUSE/py2pack/blob/master/py2pack/spdx_license_map.p , which contains both `New BSD License` and `BSD-3-Clause`.

Interesting that https://packaging.python.org/tutorials/packaging-projects/ doesnt mention using `setup(.. license='...', ..)` at all.

Semi related, we should at least be including some more [Trove classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers), including a license classifier -- probably this one...?

`License :: OSI Approved :: BSD License`

No need to rush out a new release for this, as I can manually solve this one in the .spec , but it is an interesting problem that needs to be understood and solved so that running `py2pack` on a moban powered package 'just works', to make it easier to package them (them = moban / pyexcel / etc).

**Comment by jayvdb** [comment]
https://en.opensuse.org/openSUSE:Packaging_guidelines#Spec_Files says

> Licenses should be declared using SPDX shortname format. 

There is no logic for `License:` at https://github.com/openSUSE/py2pack/blob/master/py2pack/templates/opensuse.spec

The FIXME is added at https://github.com/openSUSE/py2pack/blob/2dc675a/py2pack/__init__.py#L197

If we want to keep using "`New BSD`", my guess is we need to enhance `py2pack` to accept that the suffix "` License`" is redundant and not require it.

**Comment by jayvdb** [comment]
Note the package is now in the openSUSE devel repo, which is the feeder before it goes to the 'factory' to be included in the distro.

https://build.opensuse.org/package/show/devel:languages:python/python-lml

**Comment by jayvdb** [comment]
According to https://build.opensuse.org/request/show/666353 , the license should be "BSD-3-License", unless that isnt the one you as author intended.

This is really a byproduct of https://github.com/moremoban/pypi-mobans/issues/12 not being done yet.  License names are becoming more important, and SPDX is the 'authority'.

**Comment by chfw** [comment]
This package now includes the license.
